export enum ErrorCode {
    AUTH = "Authentication Error",
    PLAN = "Plan Error",
    CONFLICT = "Conflict",
    ALREADY_EXISTS = "Already Exists",
    ONBOARDING = "Onboarding Error",
    EMAIL_SEND_FAILED = "Email send failed!",
    EMAIL_SERVICE_UNAVAILABLE = "Email Service Unavailable!",
    OTP_RESEND_COOLDOWN = "OTP_RESEND_COOLDOWN",
    RESOURCE_NOT_FOUND = "Resource Not Found",
    INVALID_OPERATION = "Invalid Operation",
    VALIDATION = "Validation Error",
    VALIDATION_ERROR = "Validation Error",
    INTERNAL_ERROR = "Internal Error",
}